// Icon catalog. Documents store icon names (Font Awesome-style names such as
// "home", "trash", "folder-bookmark" are common in existing files); we map
// them to the open-source Lucide set. Unknown names fall back to a folder.

import type { LucideIcon, LucideProps } from "lucide-react";
import * as L from "lucide-react";

/** name → [Lucide component, search keywords] */
const CATALOG: Record<string, [LucideIcon, string]> = {
  home: [L.House, "house start"],
  house: [L.House, "home"],
  trash: [L.Trash2, "delete bin"],
  folder: [L.Folder, "directory"],
  "folder-open": [L.FolderOpen, "directory"],
  "folder-bookmark": [L.BookmarkCheck, "template"],
  bookmark: [L.Bookmark, "save"],
  briefcase: [L.Briefcase, "work job"],
  star: [L.Star, "favorite"],
  heart: [L.Heart, "love health"],
  "cart-shopping": [L.ShoppingCart, "shop buy"],
  "basket-shopping": [L.ShoppingBasket, "groceries"],
  hourglass: [L.Hourglass, "wait time"],
  bolt: [L.Zap, "quick lightning"],
  bullseye: [L.Target, "focus goal"],
  fire: [L.Flame, "urgent hot"],
  ban: [L.Ban, "blocked stop"],
  user: [L.User, "person"],
  users: [L.Users, "people team"],
  globe: [L.Globe, "web world"],
  "chart-line": [L.ChartLine, "graph stats"],
  "chart-column": [L.ChartColumn, "graph bar"],
  cloud: [L.Cloud, "someday weather"],
  repeat: [L.Repeat, "recurring routine"],
  "calendar-check": [L.CalendarCheck, "schedule done"],
  calendar: [L.Calendar, "date"],
  "graduation-cap": [L.GraduationCap, "learn school"],
  file: [L.File, "document"],
  "file-lines": [L.FileText, "document text"],
  tag: [L.Tag, "label"],
  tags: [L.Tags, "labels"],
  book: [L.Book, "read"],
  "book-open": [L.BookOpen, "read"],
  code: [L.Code, "dev programming"],
  terminal: [L.Terminal, "console"],
  music: [L.Music, "song"],
  camera: [L.Camera, "photo"],
  plane: [L.Plane, "travel flight"],
  car: [L.Car, "drive"],
  bicycle: [L.Bike, "bike cycle"],
  dumbbell: [L.Dumbbell, "gym fitness"],
  mug: [L.Coffee, "coffee break"],
  utensils: [L.Utensils, "food eat"],
  gift: [L.Gift, "present"],
  lightbulb: [L.Lightbulb, "idea"],
  rocket: [L.Rocket, "launch"],
  flag: [L.Flag, "milestone"],
  bell: [L.Bell, "reminder"],
  envelope: [L.Mail, "mail email"],
  phone: [L.Phone, "call"],
  message: [L.MessageSquare, "chat"],
  clock: [L.Clock, "time"],
  inbox: [L.Inbox, "mail"],
  box: [L.Package, "package"],
  "box-archive": [L.Archive, "archive"],
  wrench: [L.Wrench, "fix tool"],
  hammer: [L.Hammer, "build tool"],
  palette: [L.Palette, "art color design"],
  brush: [L.Brush, "paint"],
  pen: [L.PenTool, "design"],
  pencil: [L.Pencil, "write edit"],
  sparkles: [L.Sparkles, "magic new"],
  sun: [L.Sun, "day"],
  moon: [L.Moon, "night"],
  leaf: [L.Leaf, "nature"],
  tree: [L.TreePine, "nature"],
  dog: [L.Dog, "pet"],
  cat: [L.Cat, "pet"],
  baby: [L.Baby, "child"],
  stethoscope: [L.Stethoscope, "doctor health"],
  pills: [L.Pill, "medicine"],
  wallet: [L.Wallet, "money"],
  "piggy-bank": [L.PiggyBank, "savings money"],
  "money-bill": [L.Banknote, "cash money"],
  "credit-card": [L.CreditCard, "pay"],
  building: [L.Building2, "office"],
  school: [L.School, "education"],
  "building-columns": [L.Landmark, "bank government"],
  map: [L.Map, "travel"],
  "location-dot": [L.MapPin, "place"],
  compass: [L.Compass, "explore"],
  mountain: [L.Mountain, "hike"],
  water: [L.Waves, "sea"],
  gamepad: [L.Gamepad2, "game"],
  film: [L.Film, "movie"],
  tv: [L.Tv, "television"],
  headphones: [L.Headphones, "audio"],
  laptop: [L.Laptop, "computer"],
  desktop: [L.Monitor, "computer"],
  mobile: [L.Smartphone, "phone"],
  server: [L.Server, "infra"],
  database: [L.Database, "data"],
  bug: [L.Bug, "issue"],
  shield: [L.Shield, "security"],
  lock: [L.Lock, "private"],
  key: [L.Key, "access"],
  trophy: [L.Trophy, "win"],
  medal: [L.Medal, "award"],
  crown: [L.Crown, "king"],
  gem: [L.Gem, "value"],
  "puzzle-piece": [L.Puzzle, "piece"],
  brain: [L.Brain, "think"],
  seedling: [L.Sprout, "grow"],
  recycle: [L.Recycle, "eco"],
  anchor: [L.Anchor, "boat"],
  ship: [L.Ship, "boat"],
  train: [L.Train, "travel"],
  truck: [L.Truck, "delivery"],
  tent: [L.Tent, "camp"],
  umbrella: [L.Umbrella, "rain"],
  snowflake: [L.Snowflake, "winter"],
  "apple-whole": [L.Apple, "fruit"],
  "pizza-slice": [L.Pizza, "food"],
  "cake-candles": [L.Cake, "birthday"],
  "wine-glass": [L.Wine, "drink"],
  shirt: [L.Shirt, "clothes"],
  link: [L.Link, "url"],
  list: [L.List, "items"],
  "list-check": [L.ListChecks, "checklist"],
  layers: [L.Layers, "stack"],
  printer: [L.Printer, "print"],
  gear: [L.Settings, "settings"],
  eye: [L.Eye, "watch"],
  pin: [L.Pin, "pinned"],
  shapes: [L.Shapes, "misc"],
  progression: [L.CircleDashed, "progress"],
};

export const ICON_NAMES = Object.keys(CATALOG).filter((n) => n !== "progression");

export function iconKeywords(name: string): string {
  return `${name} ${CATALOG[name]?.[1] ?? ""}`;
}

export function resolveIcon(name: string | null | undefined, fallback: LucideIcon = L.Folder): LucideIcon {
  if (!name) return fallback;
  return CATALOG[name]?.[0] ?? CATALOG[name.replace(/^fa-/, "")]?.[0] ?? fallback;
}

export function Icon({ name, fallback, ...props }: { name: string | null | undefined; fallback?: LucideIcon } & Omit<LucideProps, "name">) {
  const C = resolveIcon(name, fallback);
  return <C size={16} strokeWidth={1.8} aria-hidden {...props} />;
}

